plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'io.github.electronstudio:jaylib-ffm:5.5.0-0'
    //io/github/electronstudio/jaylib-ffm/5.5.0-0/jaylib-ffm-5.5.0-0.pom
}

test {
    useJUnitPlatform()
}